/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
    './content/**/*.mdx',
  ],
  theme: {
    extend: {
      colors: {
        ivory:    '#F5F1EB',
        ink:      '#1A1410',
        resin:    '#8B6340',
        gold:     '#C4872A',
        'gold-lt':'#F0E4CC',
        spruce:   '#2C4A2E',
        border:   '#DDD5C5',
      },
      fontFamily: {
        display: ['var(--font-cormorant)', 'Georgia', 'serif'],
        sans:    ['var(--font-inter)', 'system-ui', 'sans-serif'],
        mono:    ['var(--font-jetbrains)', 'monospace'],
      },
      typography: {
        DEFAULT: {
          css: {
            color: '#1A1410',
            maxWidth: 'none',
            lineHeight: '1.75',
            a: {
              color: '#C4872A',
              textDecoration: 'none',
              fontWeight: '500',
              '&:hover': { textDecoration: 'underline' },
            },
            h2: {
              fontFamily: 'var(--font-cormorant), Georgia, serif',
              fontWeight: '600',
              fontSize: '1.6em',
              letterSpacing: '-0.01em',
              color: '#1A1410',
              marginTop: '2em',
            },
            h3: {
              fontFamily: 'var(--font-cormorant), Georgia, serif',
              fontWeight: '500',
              fontSize: '1.3em',
              color: '#1A1410',
            },
            'code': {
              fontFamily: 'var(--font-jetbrains), monospace',
              color: '#C4872A',
              backgroundColor: '#F0E4CC',
              padding: '0.1em 0.35em',
              borderRadius: '0.25em',
              fontWeight: '400',
              fontSize: '0.88em',
            },
            'code::before': { content: '""' },
            'code::after':  { content: '""' },
            blockquote: {
              borderLeftColor: '#C4872A',
              borderLeftWidth: '3px',
              fontStyle: 'italic',
              fontFamily: 'var(--font-cormorant), Georgia, serif',
              fontSize: '1.15em',
              color: '#2C4A2E',
              paddingLeft: '1.25em',
            },
            'blockquote p:first-of-type::before': { content: '""' },
            'blockquote p:last-of-type::after':   { content: '""' },
            strong: { color: '#1A1410', fontWeight: '600' },
            hr:     { borderColor: '#DDD5C5' },
            'thead th': {
              color: '#1A1410',
              fontFamily: 'var(--font-inter), system-ui, sans-serif',
              fontWeight: '600',
              fontSize: '0.8em',
              letterSpacing: '0.06em',
              textTransform: 'uppercase',
              backgroundColor: '#F0E4CC',
              paddingTop: '0.6em',
              paddingBottom: '0.6em',
            },
            'thead th:first-child': { borderRadius: '0' },
            'thead th:last-child':  { borderRadius: '0' },
            'tbody td': {
              fontFamily: 'var(--font-inter), system-ui, sans-serif',
              fontSize: '0.92em',
              color: '#1A1410',
            },
            'tbody tr': { borderBottomColor: '#DDD5C5' },
            table: { fontSize: '1em' },
          },
        },
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
}
